# Generated by Django 4.0.1 on 2022-01-30 15:32

import common.status_enum
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 15, 32, 3, 174121, tzinfo=utc))),
                ('updateAt', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 15, 32, 3, 174121, tzinfo=utc))),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[(common.status_enum.StatusType['INCOMPLETE'], 'INCOMPLETE'), (common.status_enum.StatusType['COMPLETED'], 'COMPLETED')], default=common.status_enum.StatusType['INCOMPLETE'], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
