# Generated by Django 4.0.1 on 2022-02-01 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 17, 27, 32, 477287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 17, 27, 32, 477287, tzinfo=utc)),
        ),
    ]
